---
title: FonoAPI - Mobile Devices Specifications 
subtitle: If you spend an hour now, you can save five later - Rami Hassan
author: ~
date: '2018-01-12'
slug: fonoapi
categories: [R]
tags: [API, R]
---


Recently, I had to look at different devices and their specs to build an idea about which are the best devices at the moment. As there are many types and manufacturers, I was inefficient at looking through each model on gsmarena and decided to look for a better solution. So I have stumbled upon [FonoApi](https://fonoapi.freshpixl.com/). This website provides a free token to use with their API via Python, Curl, jQuery or NodeJS to retrieve specifications about almost any device ever built. Their library is very large (includes very old phones like Nokia 5110 - released in 1998) and data is retrieved very fast which is really nice, however, they did not have a method of retrieving data using R.

At first, I have used the Python scripts provided which did the job amazingly but then I decided to re-write all this in R because I have become more familiar with R than Python in the last year (this blog is powered by R Markdown alone). 

So, I have decided the best solution for me was to create a function into which I can input the device type or device brand (or both) and the token you get from their website and obtain a dataset containing information about the said device. 

If you would like to have a shot at this, the script can be found here: [GabrielOana - FonoAPI Script](https://github.com/Gabrieloana91/FonoAPI-R-Script)

## R Code
```{r}

get_device <- function(device = NULL, brand = NULL, token){
  
  if(length(nchar(token)) == 0){
    stop("Insert a valid token from https://fonoapi.freshpixl.com/")
  }
  
  # Parameters
  library(httr)
  library(jsonlite)
  library(dplyr)
  url = "https://fonoapi.freshpixl.com/v1/getdevice"

  # Clean-UP
  device <- tolower(device)
  brand <- tolower(brand)
  
  # Conditional clause if brand or device (or both are chosen)
  if(length(nchar(brand)) == 0 & length(nchar(device)) != 0){
    
    param <- list(token = token,
                  brand = "",
                  device = device)
    
  } else if(length(nchar(brand)) != 0 & length(nchar(device)) == 0){
    
    param <- list(token = token,
                  brand = brand,
                  device = " ")
    
  } else if(length(nchar(brand)) != 0 & length(nchar(device)) != 0){
    
    param <- list(token = token,
                  brand = brand,
                  device = device)
  } else{
    
    stop("=== Insert a device/brand and the correct API Key from https://fonoapi.freshpixl.com/ ===")
    
  }
  
  # Transform the parameters into JSON format
  param <- toJSON(param)
  param <- gsub(pattern = '\\[', replacement = "", x = param)
  param <- gsub(pattern = '\\]', replacement = "", x = param)
  
  # API Call
  
  # fileName <- fromJSON(prettify(POST(url = url, add_headers(.headers = c("Content-Type"="application/json")), body = param)))
  fileName <- POST(url = url, add_headers(.headers = c("Content-Type"="application/json")), body = param)
  
  # Warning + Error Messages
  temp <- content(fileName)
  if(length(nchar(temp$message)) > 0){
    stop(temp$message)
  }
  
  # Data Structure
  fileName <- suppressMessages(fromJSON(prettify(fileName)))
  
  devices_list <<- fileName %>% 
    separate(internal, into = c("internal_memory", "ram_memory", "ram_memory2"), sep = ",", extra = "drop",  fill = "right") %>% 
    mutate(ram_memory = gsub("RAM","",coalesce(ram_memory2, ram_memory))) %>% 
    select(-ram_memory2) %>% 
    mutate(ram_memory = gsub("RAM DDR3","", ram_memory)) %>% 
    mutate(ram_memory = gsub("DDR3","", ram_memory)) 
    
}
```


